In [106]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg

In [3]:
whatever, mu_pe, mu_inc, mu_blei = np.genfromtxt("Attenuation/Blei.txt", unpack ="True", skip_header=3)

In [112]:
mu_air = 0.08039
A = 1.8E07
d_blei = 3
d_luft = 28.4
d_blende = 0.3
L = 32

In [10]:
print(mu_blei[0])


0.1103


In [118]:
Zaehlrate = A * np.exp(- (mu_blei[0]*d_blei + mu_air*d_luft)) *((1/4*np.pi*d_blende**2)/(4*np.pi*L**2))
print(Zaehlrate)

7.242020046071188


In [135]:
t= 154
count = Zaehlrate*t
unsicherheit = np.sqrt(count)/count
print(unsicherheit)
t_ziel = 1/(0.03**2 * Zaehlrate)
print(t_ziel)

0.029943997529276598
153.4255779523686


In [53]:
def cubes_to_vector(cube_numbers, diagonal=False):
    TOTAL_CUBES = 9
    vector = np.zeros(TOTAL_CUBES)
    for c in cube_numbers:
        vector[c-1] = 1
    if diagonal:
        vector *= np.sqrt(2)
    return vector

In [146]:
rows_linear = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    #[1,4,7],
    [2,5,8],
    [3,6,9]
]
rows_diagonal = [
    [1,5,9],
    [3,5,7],
    #[4,8],
    [2,6],
    #[2,4],
    [6,8],
    [7,5,3]
]
a = (list(cubes_to_vector(r) for r in rows_linear) + 
list(cubes_to_vector(r,diagonal=True) for r in rows_diagonal))

a = np.array(a)
a

array([[1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 1.        ,
        1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        ],
       [1.41421356, 0.        , 0.        , 0.        , 1.41421356,
        0.        , 0.        , 0.        , 1.41421356],
       [0.        , 0.        , 1.41421356, 0.        , 1.41421356,
        0.        , 1.41421356, 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        , 0.        ,
        1.41421356, 0.        , 0.        , 0.        ],


In [147]:
a.shape

(10, 9)

In [148]:
np.linalg.matrix_rank(a)

9

In [139]:
ainv = np.linalg.inv(a)
ainv_sp = scipy.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

In [109]:
one = np.dot(a, ainv)
one_sp = np.dot(a, ainv_sp)
print(np.array_str(one_sp, suppress_small=True))

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  1. -0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0. -0.  0.]
 [ 0. -0.  0.  0.  0.  0.  1. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -0.]
 [ 0.  0.  0. -0.  0.  0. -0.  0.  1.]]
